### ISSUE TITLE
How to contact you?

### ISSUE THREAD

**Issue by YamatoSecurity** [fukusuket/urlhaus-search#1]
@fukusuket 
Sorry I don't know how to contact you so I added this issue.
Are you interested in helping out with Hayabusa? We could use your help.
We have our next developer meeting on October 20th, 20:00 on zoom.
You can also join the #hayabusa-kaihatsu slack channel to chat with us.

https://join.slack.com/t/yamatosecurity2/shared_invite/enQtNDgzMjg4ODIyNDM5LTM2Nzg2OGIwZWVkZjI0ZmNlOWQ0OTUzOTA3MTM4YzVhNzMyYmJjNGNiZTYzYmNmNDY5ZDA3YzgxNDQzMjQ0NDU

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so match for the invitation :)  If I can be of any help, I would appreciate it 😀
I will join in slack.
